version: '3.8'

services:
  music-playlist-generator:
    build: .
    container_name: music-playlist-generator
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      # Update these paths to match your setup
      - MUSIC_JSON_PATH=/data/music_index.json
      - PLAYLIST_OUTPUT_DIR=/data/playlists
      - VIRTUAL_MUSIC_ROOT=/music
      - MUSIC_ROOT=/data/music_library
      - DOWNLOAD_DIR=/data/downloads
      - SECRET_KEY=your-generated-secret-key-here
    volumes:
      # Mount your music library (read-only)
      - /path/to/your/music/library:/data/music_library:ro
      # Mount your music index file (read-only) 
      - /path/to/your/music_index.json:/data/music_index.json:ro
      # Mount playlists directory (read-write)
      - ./playlists:/data/playlists
      # Mount downloads directory (read-write)
      - ./downloads:/data/downloads
    restart: unless-stopped
    networks:
      - music-net

networks:
  music-net:
    driver: bridge